import { Adoption } from "../../interfaces/adoption/types";

export const adoptions: Adoption[] = [
	{
		id: 59815,
		name: "새봄1",
		breed: "골든리트리버",
		gender: "암컷",
		characteristic: "",
		date: "24.05.12",
		status: 1,
	},
	{
		id: 59816,
		name: "새봄2",
		breed: "골든리트리버",
		gender: "암컷",
		characteristic: "",
		date: "24.05.12",
		status: 2,
	},
	{
		id: 59817,
		name: "새봄3",
		breed: "골든리트리버",
		gender: "암컷",
		characteristic: "",
		date: "24.05.12",
		status: 1,
	},
	{
		id: 59818,
		name: "새봄4",
		breed: "골든리트리버",
		gender: "암컷",
		characteristic: "",
		date: "24.05.12",
		status: 1,
	},
	{
		id: 59819,
		name: "새봄5",
		breed: "골든리트리버",
		gender: "암컷",
		characteristic: "",
		date: "24.05.12",
		status: 1,
	},
	{
		id: 59820,
		name: "새봄6",
		breed: "골든리트리버",
		gender: "암컷",
		characteristic: "",
		date: "24.05.12",
		status: 1,
	},
	{
		id: 59821,
		name: "새봄7",
		breed: "골든리트리버",
		gender: "암컷",
		characteristic: "",
		date: "24.05.12",
		status: 1,
	},
	{
		id: 59822,
		name: "새봄8",
		breed: "골든리트리버",
		gender: "암컷",
		characteristic: "",
		date: "24.05.12",
		status: 1,
	},
	{
		id: 59823,
		name: "새봄9",
		breed: "골든리트리버",
		gender: "암컷",
		characteristic: "",
		date: "24.05.12",
		status: 1,
	},
	{
		id: 59824,
		name: "새봄10",
		breed: "골든리트리버",
		gender: "암컷",
		characteristic: "",
		date: "24.05.12",
		status: 1,
	},
	{
		id: 59825,
		name: "새봄11",
		breed: "골든리트리버",
		gender: "암컷",
		characteristic: "",
		date: "24.05.12",
		status: 1,
	},
	{
		id: 59826,
		name: "새봄12",
		breed: "골든리트리버",
		gender: "암컷",
		characteristic: "",
		date: "24.05.12",
		status: 1,
	},
	{
		id: 59827,
		name: "새봄13",
		breed: "골든리트리버",
		gender: "암컷",
		characteristic: "",
		date: "24.05.12",
		status: 1,
	},
	{
		id: 59828,
		name: "새봄14",
		breed: "골든리트리버",
		gender: "암컷",
		characteristic: "",
		date: "24.05.12",
		status: 1,
	},
];

export const adoptionSummaryData = {
	total: 10,
	today: 3,
	completion: 1,
	waiting: 9,
};
